// Declare two variables

let num1 = 18; 
let num2 = 23;

// Perform operations and store results
let x = num1 + num2;
let y = num1 - num2;
let z = num1 * num2;
let c = num1 / num2;
let b = num1 % num2;

// Print results
   console.log("x: " + num1 + " + " + num2 + " = " + x);
   console.log("y: " + num1 + " - " + num2 + " = " + y);
   console.log("z: " + num1 + " * " + num2 + " = " + z);
   console.log("c: " + num1 + " / " + num2 + " = " + c);
   console.log("b: " + num1 + " % " + num2 + " = " + b);
